version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    env_file:
      - .env.local.backend
    depends_on:
      db:
        condition: service_healthy
    mem_limit: 512m
    cpus: 0.5
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    mem_limit: 256m
    cpus: 0.25
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:13
    container_name: db
    env_file:
      - .env.local.db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    mem_limit: 1g
    cpus: 1.0
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./frontend/build:/usr/share/nginx/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    mem_limit: 128m
    cpus: 0.25
    restart: unless-stopped

volumes:
  postgres_data:
